// examples/react-example/src/App.jsx
import React, { useState, useEffect } from 'react';
import { 
  DuckDBProvider, 
  useDuckDB, 
  useQuery, 
  useMutation,
  useImportCSV,
  useImportJSON,
  useExportCSV,
  useExportJSON,
  downloadFile,
  resultToCSV 
} from '@northprint/duckdb-wasm-adapter/react';
import QueryBuilderDemo from './components/QueryBuilderDemo';
import CacheDemo from './components/CacheDemo';
import SpatialDemo from './components/SpatialDemo';

function DuckDBExample() {
  const { connection, status, error, connect, disconnect } = useDuckDB();
  const [sqlQuery, setSqlQuery] = useState('SELECT * FROM employees');
  const [customQuery, setCustomQuery] = useState('');
  const [importFile, setImportFile] = useState(null);
  const [tableName, setTableName] = useState('imported_data');
  const [tableReady, setTableReady] = useState(false);
  
  // Setup mutation for creating initial data
  const setupMutation = useMutation();
  
  // Query hook - only run after table is ready
  const { data, loading, error: queryError, refetch } = useQuery(
    sqlQuery,
    undefined,
    { enabled: status === 'connected' && tableReady }
  );
  
  // Import hooks
  const { importCSV, loading: csvLoading } = useImportCSV();
  const { importJSON, loading: jsonLoading } = useImportJSON();
  const exportCSV = useExportCSV();
  const exportJSON = useExportJSON();
  
  // Setup initial data
  useEffect(() => {
    if (status === 'connected' && connection) {
      const setupQuery = `
        CREATE TABLE IF NOT EXISTS employees (
          id INTEGER,
          name VARCHAR,
          department VARCHAR,
          salary DECIMAL(10,2),
          hire_date DATE
        );
        
        DELETE FROM employees;
        
        INSERT INTO employees VALUES 
          (1, 'Alice Johnson', 'Engineering', 95000.00, '2020-03-15'),
          (2, 'Bob Smith', 'Sales', 75000.00, '2019-07-22'),
          (3, 'Carol White', 'Marketing', 82000.00, '2021-01-10'),
          (4, 'David Brown', 'Engineering', 105000.00, '2018-11-05'),
          (5, 'Eve Davis', 'HR', 68000.00, '2022-02-28');
      `;
      
      setupMutation.mutate(setupQuery).then(() => {
        console.log('Sample data created successfully');
        setTableReady(true); // Mark table as ready
        refetch(); // データ作成後にクエリを再実行
      }).catch(console.error);
    }
  }, [status, connection]);
  
  // Execute custom query
  const executeCustomQuery = () => {
    if (customQuery) {
      setSqlQuery(customQuery);
    }
  };
  
  // Handle file import
  const handleImport = async () => {
    if (!importFile) return;
    
    try {
      if (importFile.name.endsWith('.csv')) {
        await importCSV(importFile, tableName);
      } else if (importFile.name.endsWith('.json')) {
        const text = await importFile.text();
        const data = JSON.parse(text);
        await importJSON(data, tableName);
      }
      
      alert(`Successfully imported ${importFile.name} into table ${tableName}`);
      setSqlQuery(`SELECT * FROM ${tableName}`);
    } catch (error) {
      alert(`Import failed: ${error.message}`);
    }
  };
  
  // Export as CSV
  const handleExportCSV = async () => {
    if (!data) return;
    
    const csv = resultToCSV(data);
    downloadFile(csv, 'export.csv', 'text/csv');
  };
  
  // Export as JSON
  const handleExportJSON = async () => {
    try {
      const json = await exportJSON(sqlQuery);
      downloadFile(JSON.stringify(json, null, 2), 'export.json', 'application/json');
    } catch (error) {
      alert(`Export failed: ${error.message}`);
    }
  };
  
  const exampleQueries = [
    { label: 'All Employees', query: 'SELECT * FROM employees' },
    { label: 'High Earners', query: 'SELECT name, salary FROM employees WHERE salary > 80000' },
    { label: 'Avg Salary by Dept', query: 'SELECT department, AVG(salary) as avg_salary FROM employees GROUP BY department' },
    { label: 'Recent Hires', query: 'SELECT name, hire_date FROM employees ORDER BY hire_date DESC LIMIT 3' },
  ];
  
  return (
    <div className="container">
      <h1>🦆 DuckDB WASM React Example</h1>
      
      <section className="status-section">
        <h2>Connection Status</h2>
        <p>Status: <span className={`status-badge ${status}`}>{status}</span></p>
        {error && <p className="error">Error: {error.message}</p>}
        <div className="button-group">
          {status !== 'connected' ? (
            <button onClick={connect}>Connect</button>
          ) : (
            <>
              <button onClick={disconnect}>Disconnect</button>
              <button onClick={() => {
                const setupQuery = `
                  CREATE TABLE IF NOT EXISTS employees (
                    id INTEGER,
                    name VARCHAR,
                    department VARCHAR,
                    salary DECIMAL(10,2),
                    hire_date DATE
                  );
                  
                  DELETE FROM employees;
                  
                  INSERT INTO employees VALUES 
                    (1, 'Alice Johnson', 'Engineering', 95000.00, '2020-03-15'),
                    (2, 'Bob Smith', 'Sales', 75000.00, '2019-07-22'),
                    (3, 'Carol White', 'Marketing', 82000.00, '2021-01-10'),
                    (4, 'David Brown', 'Engineering', 105000.00, '2018-11-05'),
                    (5, 'Eve Davis', 'HR', 68000.00, '2022-02-28');
                `;
                setupMutation.mutate(setupQuery).then(() => {
                  console.log('Sample data created successfully');
                  refetch();
                }).catch(console.error);
              }}>Setup Sample Data</button>
            </>
          )}
        </div>
      </section>
      
      <section className="query-editor">
        <h2>Query Editor</h2>
        <textarea
          value={customQuery}
          onChange={(e) => setCustomQuery(e.target.value)}
          placeholder={sqlQuery}
          rows={4}
        />
        <button onClick={executeCustomQuery}>Execute Query</button>
        <button onClick={refetch}>Refresh Results</button>
      </section>
      
      <section className="import-section">
        <h2>Import Data</h2>
        <div className="import-controls">
          <input
            type="file"
            accept=".csv,.json"
            onChange={(e) => setImportFile(e.target.files[0])}
          />
          <input
            type="text"
            value={tableName}
            onChange={(e) => setTableName(e.target.value)}
            placeholder="Table name"
          />
          <button 
            onClick={handleImport} 
            disabled={!importFile || csvLoading || jsonLoading}
          >
            {csvLoading || jsonLoading ? 'Importing...' : 'Import'}
          </button>
        </div>
      </section>
      
      <section className="results-section">
        <h2>Query Results</h2>
        <p style={{ fontSize: '12px', color: '#666' }}>
          Status: {status} | Table Ready: {tableReady ? 'Yes' : 'No'} | 
          Data: {data ? `${data.length} rows` : 'No data'}
        </p>
        
        {loading && <p>Loading...</p>}
        {queryError && <p className="error">Error: {queryError.message}</p>}
        {data && data.length > 0 && (
          <>
            <div className="export-buttons">
              <button onClick={handleExportCSV}>Export as CSV</button>
              <button onClick={handleExportJSON}>Export as JSON</button>
              <button onClick={refetch}>Refresh</button>
            </div>
            
            <div className="table-wrapper">
              <table>
                <thead>
                  <tr>
                    {Object.keys(data[0]).map(column => (
                      <th key={column}>{column}</th>
                    ))}
                  </tr>
                </thead>
                <tbody>
                  {data.map((row, i) => (
                    <tr key={i}>
                      {Object.values(row).map((value, j) => (
                        <td key={j}>{value ?? 'NULL'}</td>
                      ))}
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
            
            <p className="row-count">Rows: {data.length}</p>
          </>
        )}
        {data && data.length === 0 && <p>No results</p>}
      </section>
      
      <section className="examples-section">
        <h2>Example Queries</h2>
        <div className="example-buttons">
          {exampleQueries.map((example, i) => (
            <button
              key={i}
              onClick={() => setSqlQuery(example.query)}
            >
              {example.label}
            </button>
          ))}
        </div>
      </section>

      <section className="query-builder-section">
        <QueryBuilderDemo />
      </section>

      <section className="cache-section">
        <CacheDemo />
      </section>

      <section className="spatial-section">
        <SpatialDemo />
      </section>
    </div>
  );
}

function App() {
  // Enable debug mode for development
  const debugConfig = {
    enabled: true,
    logQueries: true,
    logTiming: true,
    slowQueryThreshold: 50, // 50ms
    logMemory: true,
    profileQueries: false, // Set to true for detailed profiling
  };

  // Enable cache for better performance
  const cacheConfig = {
    enabled: true,
    options: {
      maxEntries: 50,
      ttl: 60000, // 1 minute
      evictionStrategy: 'lru',
      enableStats: true,
    }
  };
  
  return (
    <DuckDBProvider 
      autoConnect 
      debug={debugConfig}
      config={{ cache: cacheConfig }}
    >
      <DuckDBExample />
    </DuckDBProvider>
  );
}

export default App;

// examples/svelte-example/src/App.svelte
<script>
  import { createDuckDB, downloadFile, resultToCSV } from '@northprint/duckdb-wasm-adapter/svelte';
  import { onMount } from 'svelte';

  // Create DuckDB instance
  const db = createDuckDB();
  
  // Extract individual stores - these are Svelte stores
  const connection = db.connection;
  const status = db.status;
  const error = db.error;
  
  let sqlQuery = 'SELECT * FROM employees';
  let customQuery = 'SELECT * FROM employees';
  let importFile = null;
  let tableName = 'imported_data';
  
  // Sample data creation query
  const setupQuery = `
    CREATE TABLE IF NOT EXISTS employees (
      id INTEGER,
      name VARCHAR,
      department VARCHAR,
      salary DECIMAL(10,2),
      hire_date DATE
    );
    
    INSERT INTO employees VALUES 
      (1, 'Alice Johnson', 'Engineering', 95000.00, '2020-03-15'),
      (2, 'Bob Smith', 'Sales', 75000.00, '2019-07-22'),
      (3, 'Carol White', 'Marketing', 82000.00, '2021-01-10'),
      (4, 'David Brown', 'Engineering', 105000.00, '2018-11-05'),
      (5, 'Eve Davis', 'HR', 68000.00, '2022-02-28');
  `;
  
  let setupComplete = false;
  
  // Setup initial data
  $: if ($connection && !setupComplete) {
    setupComplete = true;
    $connection.execute(setupQuery).catch(console.error);
  }
  
  onMount(async () => {
    console.log('App mounted, connecting to database...');
    try {
      await db.connect();
      console.log('Database connected successfully');
    } catch (error) {
      console.error('Failed to connect to database:', error);
    }
  });
  
  // Create reactive query - only when connected
  $: queryStore = $connection ? db.query(sqlQuery) : null;
  
  // Execute custom query
  async function executeCustomQuery() {
    if (!customQuery || !$connection) {
      console.log('Cannot execute query:', { customQuery, connection: $connection });
      return;
    }
    console.log('Executing query:', customQuery);
    sqlQuery = customQuery;
  }
  
  // Handle file import
  async function handleImport() {
    if (!importFile || !$connection) return;
    
    try {
      if (importFile.name.endsWith('.csv')) {
        await db.importCSV(importFile, tableName);
      } else if (importFile.name.endsWith('.json')) {
        const text = await importFile.text();
        const data = JSON.parse(text);
        await db.importJSON(data, tableName);
      }
      
      alert(`Successfully imported ${importFile.name} into table ${tableName}`);
      sqlQuery = `SELECT * FROM ${tableName}`;
    } catch (error) {
      alert(`Import failed: ${error.message}`);
    }
  }
  
  // Export data as CSV
  async function exportAsCSV() {
    if (!$queryStore.data) return;
    
    const csv = resultToCSV($queryStore.data);
    downloadFile(csv, 'export.csv', 'text/csv');
  }
  
  // Export data as JSON
  async function exportAsJSON() {
    if (!$connection) return;
    
    try {
      const json = await db.exportJSON(sqlQuery);
      downloadFile(JSON.stringify(json, null, 2), 'export.json', 'application/json');
    } catch (error) {
      alert(`Export failed: ${error.message}`);
    }
  }
</script>

<main>
  <h1>🦆 DuckDB WASM Svelte Example</h1>
  
  <section class="status">
    <h2>Connection Status</h2>
    <p>Status: <span class="status-badge {$status}">{$status}</span></p>
    {#if $error}
      <p class="error">Error: {$error.message}</p>
    {/if}
    {#if $status !== 'connected'}
      <button on:click={() => db.connect()}>Connect to Database</button>
    {:else}
      <button on:click={() => db.disconnect()}>Disconnect</button>
    {/if}
  </section>
  
  <section class="query-editor">
    <h2>Query Editor</h2>
    <textarea 
      bind:value={customQuery} 
      placeholder="Enter SQL query..."
      rows="4"
    />
    <button on:click={executeCustomQuery}>Execute Query</button>
  </section>
  
  <section class="import">
    <h2>Import Data</h2>
    <div class="import-controls">
      <input 
        type="file" 
        accept=".csv,.json" 
        on:change={(e) => importFile = e.target.files[0]}
      />
      <input 
        type="text" 
        bind:value={tableName} 
        placeholder="Table name"
      />
      <button on:click={handleImport} disabled={!importFile}>
        Import
      </button>
    </div>
  </section>
  
  <section class="results">
    <h2>Query Results</h2>
    
    {#if !queryStore}
      <p>Not connected to database</p>
    {:else if $queryStore.loading}
      <p>Loading...</p>
    {:else if $queryStore.error}
      <p class="error">Error: {$queryStore.error.message}</p>
    {:else if $queryStore.data && $queryStore.data.length > 0}
      <div class="export-buttons">
        <button on:click={exportAsCSV}>Export as CSV</button>
        <button on:click={exportAsJSON}>Export as JSON</button>
      </div>
      
      <div class="table-wrapper">
        <table>
          <thead>
            <tr>
              {#each Object.keys($queryStore.data[0]) as column}
                <th>{column}</th>
              {/each}
            </tr>
          </thead>
          <tbody>
            {#each $queryStore.data as row}
              <tr>
                {#each Object.values(row) as value}
                  <td>{value ?? 'NULL'}</td>
                {/each}
              </tr>
            {/each}
          </tbody>
        </table>
      </div>
      
      <p class="row-count">Rows: {$queryStore.data.length}</p>
    {:else}
      <p>No results</p>
    {/if}
  </section>
  
  <section class="examples">
    <h2>Example Queries</h2>
    <div class="example-buttons">
      <button on:click={() => sqlQuery = 'SELECT * FROM employees'}>
        All Employees
      </button>
      <button on:click={() => sqlQuery = 'SELECT name, salary FROM employees WHERE salary > 80000'}>
        High Earners
      </button>
      <button on:click={() => sqlQuery = 'SELECT department, AVG(salary) as avg_salary FROM employees GROUP BY department'}>
        Avg Salary by Dept
      </button>
      <button on:click={() => sqlQuery = 'SELECT name, hire_date FROM employees ORDER BY hire_date DESC LIMIT 3'}>
        Recent Hires
      </button>
    </div>
  </section>
</main>

<style>
  :global(body) {
    margin: 0;
    padding: 0;
    font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, sans-serif;
    background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
    min-height: 100vh;
  }
  
  main {
    max-width: 1200px;
    margin: 0 auto;
    padding: 2rem;
  }
  
  h1 {
    color: white;
    text-align: center;
    margin-bottom: 2rem;
    font-size: 2.5rem;
    text-shadow: 2px 2px 4px rgba(0,0,0,0.2);
  }
  
  section {
    background: white;
    border-radius: 12px;
    padding: 1.5rem;
    margin-bottom: 1.5rem;
    box-shadow: 0 4px 6px rgba(0,0,0,0.1);
  }
  
  h2 {
    margin-top: 0;
    color: #333;
    border-bottom: 2px solid #667eea;
    padding-bottom: 0.5rem;
  }
  
  .status-badge {
    padding: 0.25rem 0.75rem;
    border-radius: 20px;
    font-weight: bold;
    text-transform: uppercase;
    font-size: 0.875rem;
  }
  
  .status-badge.idle {
    background: #e0e0e0;
    color: #666;
  }
  
  .status-badge.connecting {
    background: #fff3cd;
    color: #856404;
  }
  
  .status-badge.connected {
    background: #d4edda;
    color: #155724;
  }
  
  .status-badge.error {
    background: #f8d7da;
    color: #721c24;
  }
  
  .status-badge.disconnected {
    background: #cce5ff;
    color: #004085;
  }
  
  textarea {
    width: 100%;
    padding: 0.75rem;
    border: 2px solid #e0e0e0;
    border-radius: 8px;
    font-family: 'Courier New', monospace;
    font-size: 14px;
    resize: vertical;
  }
  
  textarea:focus {
    outline: none;
    border-color: #667eea;
  }
  
  button {
    background: #667eea;
    color: white;
    border: none;
    padding: 0.75rem 1.5rem;
    border-radius: 8px;
    cursor: pointer;
    font-size: 1rem;
    transition: background 0.3s;
    margin: 0.5rem 0.5rem 0.5rem 0;
  }
  
  button:hover:not(:disabled) {
    background: #5a67d8;
  }
  
  button:disabled {
    opacity: 0.5;
    cursor: not-allowed;
  }
  
  .import-controls {
    display: flex;
    gap: 1rem;
    align-items: center;
    flex-wrap: wrap;
  }
  
  input[type="file"] {
    padding: 0.5rem;
  }
  
  input[type="text"] {
    padding: 0.75rem;
    border: 2px solid #e0e0e0;
    border-radius: 8px;
    font-size: 1rem;
  }
  
  input[type="text"]:focus {
    outline: none;
    border-color: #667eea;
  }
  
  .export-buttons {
    margin-bottom: 1rem;
  }
  
  .table-wrapper {
    overflow-x: auto;
    margin: 1rem 0;
  }
  
  table {
    width: 100%;
    border-collapse: collapse;
  }
  
  th, td {
    padding: 0.75rem;
    text-align: left;
    border-bottom: 1px solid #e0e0e0;
  }
  
  th {
    background: #f8f9fa;
    font-weight: bold;
    color: #333;
  }
  
  tr:hover {
    background: #f8f9fa;
  }
  
  .row-count {
    color: #666;
    font-size: 0.875rem;
    margin-top: 1rem;
  }
  
  .error {
    color: #dc3545;
    padding: 0.75rem;
    background: #f8d7da;
    border-radius: 8px;
    margin: 0.5rem 0;
  }
  
  .example-buttons {
    display: flex;
    flex-wrap: wrap;
    gap: 0.5rem;
  }
  
  .example-buttons button {
    background: #764ba2;
    font-size: 0.875rem;
    padding: 0.5rem 1rem;
  }
  
  .example-buttons button:hover {
    background: #5e3a85;
  }
</style>
